In [2]:
import cv2
import numpy as np
from keras.models import load_model
model=load_model("C:/Users/Jay Patel/Downloads/mask-detection.hdf5")

results={1:'without mask',0:'mask'}
GR_dict={1:(0,0,255),0:(0,255,0)}

rect_size = 4
cap = cv2.VideoCapture(0)


haarcascade = cv2.CascadeClassifier('C:/Anaconda/Library/etc/haarcascades/haarcascade_eye.xml') 
#haarcascade_frontalface_default.xml
#haarcascade_eye.xml

while True:
    (rval, im) = cap.read()
    im=cv2.flip(im,1,1) 
    
    rerect_size = cv2.resize(im, (im.shape[1] // rect_size, im.shape[0] // rect_size))
    faces = haarcascade.detectMultiScale(rerect_size)
    
    for f in faces:
        (x, y, w, h) = [v * rect_size for v in f]
        """
        face_img = im[y:y+h, x:x+w]
        rerect_sized = cv2.resize(face_img,(150,150))
        normalized = rerect_sized/255.0
        reshaped = np.reshape(normalized,(1,150,150,3))
        reshaped = np.vstack([reshaped])
        result = model.predict(reshaped)
        """
        reshaped = np.reshape(im,(1,480,640,3))
        result = model.predict(reshaped)
        
        print(result)
        
        label=np.argmax(result,axis=1)[0]
      
        cv2.rectangle(im,(x,y),(x+w,y+h),GR_dict[label],2)
        cv2.rectangle(im,(x,y-40),(x+w,y),GR_dict[label],-1)
        cv2.putText(im, results[label], (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.8,(255,255,255),2)

    cv2.imshow('LIVE',   im)
    key = cv2.waitKey(10)
    
    if key == 27: 
        break

cap.release()

cv2.destroyAllWindows()

[[0.20543005 0.79456997]]
[[0.07829744 0.9217026 ]]
[[0.18926254 0.81073743]]
[[0.13048989 0.86951005]]
[[0.25564578 0.7443542 ]]
[[0.20408882 0.7959112 ]]
[[0.22004107 0.7799589 ]]
[[0.23630473 0.7636953 ]]
[[0.22789589 0.77210414]]
[[0.15394475 0.8460552 ]]
[[0.2096019 0.7903981]]
[[0.20797922 0.7920208 ]]
[[0.18545353 0.8145464 ]]
[[0.14691989 0.8530801 ]]
[[0.15407877 0.8459212 ]]
[[0.16547948 0.8345205 ]]
[[0.11156986 0.8884301 ]]
[[0.15863332 0.84136665]]
[[0.20724371 0.7927563 ]]
[[0.14734495 0.85265505]]
[[0.18095164 0.81904835]]
[[0.13183196 0.86816806]]
[[0.26327363 0.73672634]]
[[0.3918533 0.6081466]]
[[0.89494514 0.10505483]]
[[0.8853345  0.11466554]]
[[0.9047313  0.09526873]]
[[0.90837955 0.09162043]]
[[0.91403913 0.08596089]]
[[0.91184306 0.08815694]]
[[0.8668009  0.13319907]]
[[0.8546995  0.14530055]]
[[0.892839   0.10716106]]
[[0.8911081  0.10889192]]
[[0.80886495 0.19113506]]
[[0.63996917 0.36003083]]
[[0.88325214 0.1167478 ]]
[[0.8413845  0.15861553]]
[[0.87537396 0.1

In [ ]:
import cv2

cascPath = "C:/Anaconda/Library/etc/haarcascades/haarcascade_frontalface_default.xml"
eyePath = "C:/Anaconda/Library/etc/haarcascades/haarcascade_eye.xml"
smilePath = "C:/Anaconda/Library/etc/haarcascades/haarcascade_smile.xml"

faceCascade = cv2.CascadeClassifier(cascPath)
eyeCascade = cv2.CascadeClassifier(eyePath)
smileCascade = cv2.CascadeClassifier(smilePath)

font = cv2.FONT_HERSHEY_SIMPLEX
video_capture = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = video_capture.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = frame[y:y+h, x:x+w]
        

    faces = faceCascade.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(200, 200),
        flags=cv2.CASCADE_SCALE_IMAGE
    )

    # Draw a rectangle around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 3)
        
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        cv2.putText(frame,'Face',(x, y), font, 2,(255,0,0),5)

    smile = smileCascade.detectMultiScale(
        roi_gray,
        scaleFactor= 1.16,
        minNeighbors=35,
        minSize=(25, 25),
        flags=cv2.CASCADE_SCALE_IMAGE
    )

    for (sx, sy, sw, sh) in smile:
        cv2.rectangle(roi_color, (sh, sy), (sx+sw, sy+sh), (255, 0, 0), 2)
        cv2.putText(frame,'Smile',(x + sx,y + sy), 1, 1, (0, 255, 0), 1)

    eyes = eyeCascade.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
        cv2.putText(frame,'Eye',(x + ex,y + ey), 1, 1, (0, 255, 0), 1)

    cv2.putText(frame,'Number of Faces : ' + str(len(faces)),(40, 40), font, 1,(255,0,0),2)      
    # Display the resulting frame
    cv2.imshow('Video', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the capture
video_capture.release()
cv2.destroyAllWindows()